Fix for shibboleth errors
Fixes for the following errors:

——

A NoMethodError occurred in omniauth_callbacks#shibboleth:

undefined method `confirmed_at' for nil:NilClass
app/controllers/users/omniauth_callback_controller.rb:16:in
`shibboleth'

——

An ActionView::MissingTemplate occurred in
omniauth_callbacks#shibboleth:

Missing template users/omniauth_callbacks/shibboleth,
devise/omniauth_callbacks/shibboleth, devise/shibboleth,
application/shibboleth with {:locale=>[:en], :formats=>[:html],
:handlers=>[:erb, :builder, :arb]}

——

A NoMethodError occurred in omniauth_shibboleth_request#redirect:

undefined method `wayfless_entity' for nil:NilClass
app/controllers/users/omniauth_shibboleth_request_controller.rb:6:in
`redirect'

——

Missing template error corrected by adding catch-all redirect (to root
path) at the end of the method. Undefined method for nil:NilClass
errors corrected with checks that relevant entities are not nil.